### ISSUE TITLE
Create a Rust port

### ISSUE THREAD

**Issue by dabreegster** [zonebuilders/zonebuilder#34]
@Robinlovelace and I plan to do pair programming for this, as a learning exercise. I'll try to break things down into steps/tasks here.

# Part 1: core library

The API is two functions, to produce a clockboard and a grid. The clockboard function only needs one required bit of input: the city center. There are lots of optional params -- the number of segments, number of rings, sequence of ring radii, and a city boundary to clip to. The output is a list of polygons, with attributes labeling the ring and segment. We can use the [geo crate](crates.io/crates/geo) to represent everything. https://crates.io/crates/geo-booleanop will handle the clipping. These are all pure Rust, so they'll build on any platform without dependencies, including WASM. We can assume the input is WGS84.

- [x] Start the boilerplate for a new crate
- [x] Write the API. Talk about patterns for optional params. Bring in the geo and geojson dependencies.
- [x] Implement clockboard -- it should be some fairly straightforward trig to generate the polygon points.
- [ ] Implement the grid zoning
- [ ] Start some unit tests. Checking the full polygons generated is kind of a weird test, amounting to a goldenfile. But we could assert that the number of generated polygons matches a simple formula based on the input params. And we could maybe check that the distance of the polygon's points is within the expected radius of the city center.

# Part 2: CLI tool

I'm not yet sure what this should do, but roughly the goal is convenience. Maybe you could just say `generate_clockboard amsterdam`, use something like https://github.com/osm-without-borders/cosmogony/ to grab the city center and boundary for Amsterdam, run the algorithm with default params, and write a single geojson file.

More ideas for grabbing a boundary using a name:

- https://osm-boundaries.com/
- Using Overpass (like https://help.openstreetmap.org/questions/66501/how-to-get-settlement-boundaries-from-overpass-turbo)

# Part 3: R integration

R has lots of libraries for grabbing OSM boundaries already, so maybe this is more useful to do before the CLI tool. Use https://github.com/extendr/extendr to talk to the Rust lib.

**Comment by Robinlovelace** [comment]
Good progress on this: https://github.com/zonebuilders/zonebuilder-rust
